document.write('<div class="fixed-top">');
document.write('        <nav class="navbar navbar-togglable bg-nav bg-white py-0 header-shadow py-1">');
document.write('            <div class="container position-relative jutify-content-center d-fex overflow-hidden">');
document.write('                <!-- navbar-collapse -->');
document.write('                <div class="text-uppercase" id="navbar" style="position: absolute; z-index: 99;">');
document.write('                    <div id="ham_menu" class="navigation">');
document.write('                        <input type="checkbox" name="checkbox_menu" id="navi-toggle" class="navigation__checkbox">');
document.write('                        <label for="navi-toggle" class="navigation__button menu_main_link m-0">');
document.write('                            <span class="navigation__icon" style="left:0px">');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                                <span class="navigation__icon-span"></span>');
document.write('                            </span>');
document.write('                        </label>');
document.write('                        <div class="nav_m menu_main_link"><a href="">Menu</a></div>');
document.write('                        <div id="portfolio_ttl_wrapper">');
document.write('                            <ul class="m-0 p-0">');
document.write('                                <li class="navigation__item">');
document.write('                                    <a id="portfolio_menus" href="javascript:void(0)"');
document.write('                                        class="navigation__link dropdown port_main_link home_nav menu_local_link">Our');
document.write('                                        Portfolio</a>');
document.write('                                </li>');
document.write('                            </ul>');
document.write('                        </div>');
document.write('                        <div class="navigation__background"></div>');
document.write('                        <nav class="navigation__nav">');
document.write('                            <!-- MENU HEADER STARTS -->');
document.write('                            <div class="menu_header">');
document.write('                                <div id="portfolio_ttl_wrapper">');
document.write('                                    <ul class="m-0 p-0">');
document.write('                                        <li class="navigation__item">');
document.write('                                            <a id="portfolio_menus" href="javascript:void(0)"');
document.write('                                                class="navigation__link dropdown mobile_h port_inner_link ham_link menu_local_link el_active text-uppercase">Our');
document.write('                                                Portfolio</a>');
document.write('                                            <a href="javascript:void(0)"');
document.write('                                                class="navigation__link main_menu mobile_h main_inner_link ham_link menu_local_link el_inactive text-uppercase">Menu</a>');
document.write('                                        </li>');
document.write('                                    </ul>');
document.write('                                </div>');
document.write('                                <div class="menu_logo_wrapper">');
document.write('<a href="../index.html">');
document.write('                                    <img src="../src/images/nav-logo.png" class="img-fluid animated fadeInUp" alt="AJ Design"');
document.write('                                        title="AJ Design" />');
document.write('</a>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                            <!-- MENU HEADER ENDS -->');
document.write('                            <!-- MAIN MENU STARTS -->');
document.write('                            <ul class="navigation__list">');
document.write('                                <li class="navigation__item py-3">');
document.write('                                    <a href="../index.html"');
document.write('                                        class="navigation__link mn_link ham_link menu_local_link">Home</a>');
document.write('                                </li>');
document.write('                                <li class="navigation__item mobile_none py-3">');
document.write('                                    <a id="portfolio_menus" href="javascript:void(0)"');
document.write('                                        class="navigation__link dropdown mobile_port_link ham_link menu_local_link">Our');
document.write('                                        Portfolio</a>');
document.write('                                </li>');
document.write('                                <li class="navigation__item py-3">');
document.write('                                    <a href="../aboutus/"');
document.write('                                        class="navigation__link mn_link ham_link menu_local_link">About Us</a>');
document.write('                                </li>');
document.write('                                <li class="navigation__item py-3">');
document.write('                                    <a href="../faqs/"');
document.write('                        class="navigation__link mn_link ham_link menu_local_link">FAQ’s</a>');
document.write('                </li>');
document.write('                <li class="navigation__item py-3">');
document.write('                    <a href="../contactus/"');
document.write('                        class="navigation__link mn_link ham_link menu_local_link">Contact us</a>');
document.write('                </li>');
document.write('            </ul>');
document.write('            <!-- MAIN MENU ENDS -->');
document.write('            <div class="row my_submenu_wrapper portfolio_menus el_inactive">');
document.write('                <div class="col-md-5 my_submenu_list animate__animated animate__fadeInLeftBig">');
document.write('                    <div class="inner_menu">');
document.write('                        <p class="menu_title_name"><span>Portfolio</span></p>');
document.write('                        <!-- Menus For Desktop View Starts -->');
document.write('                        <div class="menu_desktop_only">');
document.write('                            <p class="m-0 py-3"><a href="javascript:void(0)" id="Still_Images"');
document.write('                                    class="sb_mnu new_s_menu sub_menu animate__animated animate__fadeInLeft ham_link menu_local_link">Still');
document.write('                                    Images</a></p>');
document.write('                            <p class="m-0 py-3"><a href="javascript:void(0)" id="Video_Animations"');
document.write('                                    class="sb_mnu new_s_menu sub_menu  animate__animated animate__fadeInLeft ham_link menu_local_link">Video');
document.write('                                    Animations</a></p>');
document.write('                            <p class="m-0 py-3"><a href="javascript:void(0)" id="Concept_Animations"');
document.write('                                    class="sb_mnu new_s_menu sub_menu  animate__animated animate__fadeInLeft ham_link menu_local_link">Concept');
document.write('                                    Animations</a></p>');
document.write('                            <p class="m-0 py-3"><a href="javascript:void(0)" id="Interactive_Animation"');
document.write('                                    class="sb_mnu new_s_menu sub_menu  animate__animated animate__fadeInLeft ham_link menu_local_link">Interactive');
document.write('                                    Animation</a></p>');
document.write('                        </div>');
document.write('                        <!-- Menus For Desktop View Ends -->');
document.write('                        <!-- Menus For Mobile,Ipad View Starts -->');
document.write('                        <div class="menu_mobile_only">');
document.write('                            <a href="../still-images/"');
document.write('                                class="sub_menu animate__animated animate__fadeInLeft ham_link menu_local_link py-3">Still');
document.write('                                Images</a>');
document.write('                            <a href="../video-animations/"');
document.write('                                class="sub_menu animate__animated animate__fadeInLeft ham_link menu_local_link py-3">Video');
document.write('                                Animations</a>');
document.write('                            <a href="../concept-animation/"');
document.write('                                class="sub_menu animate__animated animate__fadeInLeft ham_link menu_local_link py-3">Concept');
document.write('                                Animations</a>');
document.write('                            <a href="../interactive-animation/"');
document.write('                                class="sub_menu animate__animated animate__fadeInLeft ham_link menu_local_link py-3">Interactive');
document.write('                                Animation</a>');
document.write('                        </div>');
document.write('                        <!-- Menus For Mobile,Ipad View Ends -->');
document.write('                    </div>');
document.write('                </div>');
document.write('                <div');
document.write('                    class="col-md-7 my_submenu_content  animate__animated animate__fadeInRightBig pdlr0 menu_desktop_only">');
document.write('                    <div class="inner_menu_content">');
document.write('                <div class="Still_Images_content  menu_content el_active animate__animated animate__fadeIn"');
document.write('                    style="background-image: url(../src/still-images/still-menu.png);">');
document.write('                    <a href="../still-images/" class="btn btn-primary btn-lg rounded-pill px-5 py-3 text-uppercase py-2 no-shadow font-weight-normal text-dark d-inline-block"><small>Explore</small></a>');
document.write('                </div>');

document.write('                <div class="Video_Animations_content  menu_content  animate__animated animate__fadeIn">');
document.write('                    <video onclick="javascript:void(0)" playsinline="true" autoplay="true" loop="true" muted="true" class="slider-video " id="vid_animation_vid"');
document.write('                    style="visibility: visible;" src="../src/videos/video-menu.mp4"');
document.write('                    type="video/mp4"> </video>');
document.write('                    <a href="../video-animations/" class="btn btn-primary btn-lg rounded-pill px-5 py-3 text-uppercase py-2 no-shadow font-weight-normal text-dark d-inline-block"><small>Explore</small></a>');
document.write('                </div>');

document.write('                <div class="Concept_Animations_content  menu_content  animate__animated animate__fadeIn">');
document.write('                    <video onclick="javascript:void(0)" playsinline="true" autoplay="true" loop="true" muted="true" class="slider-video " id="vid_animation_vid"');
document.write('                    style="visibility: visible;" src="../src/concept/concept-menu.mp4"');
document.write('                    type="video/mp4"></video>');
document.write('                    <a href="../concept-animation/" class="btn btn-primary btn-lg rounded-pill px-5 py-3 text-uppercase py-2 no-shadow font-weight-normal text-dark d-inline-block"><small>Explore</small></a>');
document.write('                </div>');

document.write('                <div class="Interactive_Animation_content  menu_content  animate__animated animate__fadeIn">');
document.write('                    <embed src="../interactive-animation/rcj-rn-r-11516//animation.html">');
document.write('                    <a href="../interactive-animation/" class="btn btn-primary btn-lg rounded-pill px-5 py-3 text-uppercase py-2 no-shadow font-weight-normal text-dark d-inline-block"><small>Explore</small></a>');
document.write('                </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </nav>');
document.write('    </div>');
// document.write('    <section class="Push-menus">');
// document.write('        <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-close bg-light" id="cbp-spmenu-s1">');
// document.write('            <a href="javascript:void(0);" class="menu_back_button"');
// document.write('                style="float: right;padding: 0 5px;"><i class="fa fa-chevron-left"');
// document.write('                    style="font-size:16px"></i></a>');
// document.write('            <ul class="push-menu-ul mt-5">');
// document.write('                <li> <a href="http://www.thecadco.com/" class="push-active-menu" title="Home">Home</a>');
// document.write('                </li>');
// document.write('                <li> <a href="http://www.thecadco.com/site/order/index">Services </a></li>');
// document.write('                <li><a href="http://www.thecadco.com/site/pages/content_aboutus" title="About Us">About');
// document.write('                        Us </a></li>');
// document.write('                <li><a href="http://www.thecadco.com/site/pages/faq" title="FAQ’s"> FAQ’s </a></li>');
// document.write('                <li><a href="http://www.thecadco.com/site/pages/howtouse" title="How to use website">');
// document.write('                        How to use website');
// document.write('                    </a></li>');
// document.write('                <li><a href="http://www.thecadco.com/site/pages/contactus" title="Contact us">Contact us');
// document.write('                    </a></li>');
// document.write('            </ul>');
// document.write('        </div>');
// document.write('        <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-close3 bg-light content demo-y  mCustomScrollbar _mCS_1 mCS_no_scrollbar"');
// document.write('            id="cbp-spmenu-s3">');
// document.write('            <div id="mCSB_1" class="mCustomScrollBox mCS-light-2 mCSB_vertical mCSB_inside"');
// document.write('                style="max-height: none;" tabindex="0">');
// document.write('                <div id="mCSB_1_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y"');
// document.write('                    style="position:relative; top:0; left:0;" dir="ltr">');
// document.write('                    <div class="push-category-bg ">');
// document.write('                        <h3>Portfolio <a href="javascript:void(0);" class="menu_back_button"');
// document.write('                                style="float: right;padding: 0px 0px;z-index:600"><i');
// document.write('                                    class="fa fa-chevron-left"');
// document.write('                                    style="font-size:16px;color:#ffffff;"></i></a></h3>');

// document.write('                                        <ul class="push-portfolio-ul  text-center p-0 ">');
// document.write('                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/MjY%3D"');
// document.write('                                    title="Still Images">');
// document.write('                                    <img src="./The CAD Co_files/1834481163_thumb.png"');
// document.write('                                        class="img-fluid mCS_img_loaded">');
// document.write('                                    <p><span>Still Images</span></p>');
// document.write('                                </a>');
// document.write('                            </li>');
// document.write('                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/Mjc%3D"');
// document.write('                                    title="Video Animations">');
// document.write('                                    <img src="./The CAD Co_files/1834481163_thumb.png"');
// document.write('                                        class="img-fluid mCS_img_loaded">');
// document.write('                                    <p><span>Video Animations</span></p>');
// document.write('                                </a>');
// document.write('                            </li>');
// document.write('                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/Mjk%3D"');
// document.write('                                    title="Concept Animations">');
// document.write('                                    <img src="./The CAD Co_files/1834481163_thumb.png"');
// document.write('                                        class="img-fluid mCS_img_loaded">');
// document.write('                                    <p><span>Concept Animations</span></p>');
// document.write('                                </a>');
// document.write('                            </li>');
// document.write('                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/MzA%3D"');
// document.write('                                    title="Interactive Animation">');
// document.write('                                    <img src="./The CAD Co_files/1834481163_thumb.png"');
// document.write('                                        class="img-fluid mCS_img_loaded">');
// document.write('                                    <p><span>Interactive Animation</span></p>');
// document.write('                                </a>');
// document.write('                            </li>');
// document.write('                        </ul>');
// document.write('                    </div>');

// document.write('               </div>');
// document.write('            </div>');
// document.write('        </div>');
// document.write('        <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-close4  bg-light  content demo-y mCustomScrollbar _mCS_2 mCS_no_scrollbar"');
// document.write('            id="cbp-spmenu-s4">');
// document.write('            <div id="mCSB_2" class="mCustomScrollBox mCS-light-2 mCSB_vertical mCSB_inside" tabindex="0"');
// document.write('                style="max-height: none;">');
// document.write('                <div id="mCSB_2_container" class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y"');
// document.write('                    style="position:relative; top:0; left:0;" dir="ltr">');
// document.write('                    <div class="push-mob-acd ">');
// document.write('                        <div id="accordion">');
// document.write('                            <div class="card">');
// document.write('                                <div class="card-header" id="headingOne">');
// document.write('                                    <h5 class="mb-0">');
// document.write('                                        <button class="btn btn-link collapsed acd-btn-menu "');
// document.write('                                            data-toggle="collapse" data-target="#collapseOne"');
// document.write('                                            aria-expanded="false" aria-controls="collapseOne">');
// document.write('                                            MENU');
// document.write('                                        </button>');
// document.write('                                    </h5>');
// document.write('                                </div>');
// document.write('                                <div id="collapseOne" class="collapse" aria-labelledby="headingOne"');
// document.write('                                    data-parent="#accordion">');
// document.write('                                    <div class="card-body">');
// document.write('                                        <ul class="push-menu-ul ">');
// document.write('                                            <li> <a href="http://www.thecadco.com/"');
// document.write('                                                    class="push-active-menu">Home </a></li>');
// document.write('                                            <li> <a href="http://www.thecadco.com/site/order/index">Services');
// document.write('                                                </a></li>');
// document.write('                                            <li><a');
// document.write('                                                    href="http://www.thecadco.com/site/pages/content_aboutus">About');
// document.write('                                                    Us</a></li>');
// document.write('                                            <li><a href="http://www.thecadco.com/site/pages/faq"> FAQ’s');
// document.write('                                                </a></li>');
// document.write('                                            <li><a href="http://www.thecadco.com/site/pages/contactus">Contact');
// document.write('                                                    us </a></li>');
// document.write('                                        </ul>');
// document.write('                                    </div>');
// document.write('                                </div>');
// document.write('                            </div>');
// document.write('                            <div class="card">');
// document.write('                                <div class="card-header" id="headingTwo">');
// document.write('                                    <h5 class="mb-0">');
// document.write('                                        <button class="btn btn-link collapsed acd-btn-menu"');
// document.write('                                            data-toggle="collapse" data-target="#collapseTwo"');
// document.write('                                            aria-expanded="false" aria-controls="collapseTwo">');
// document.write('                                            OUR PORTFOLIO');
// document.write('                                        </button>');
// document.write('                                    </h5>');
// document.write('                                </div>');
// document.write('                                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"');
// document.write('                                    data-parent="#accordion">');
// document.write('                                    <div class="card-body p-0">');
// document.write('                                        <h3 class="mob-push-cat">PORTFOLIO</h3>');
// document.write('                                        <ul class="push-portfolio-ul   text-center p-0 ">');
// document.write('                                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/MjY%3D"');
// document.write('                                                    title="Still Images">');
// document.write('                                                    <img src="./The CAD Co_files/68512604_thumb.png"');
// document.write('                                                        class="img-fluid mCS_img_loaded">');
// document.write('                                                    <p>Still Images</p>');
// document.write('                                                </a>');
// document.write('                                            </li>');
// document.write('                                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/Mjc%3D"');
// document.write('                                                    title="Video Animations">');
// document.write('                                                    <video autoplay="" loop="" muted=""');
// document.write('                                                        class="img-image"');
// document.write('                                                        style="height: 112px;visibility: visible;">');
// document.write('                                                        <source');
// document.write('                                                            src="http://cdn.thecadco.com.s3.amazonaws.com/assets/admin/uploads/doc/portfolio/27/1062957923_thumb.mp4"');
// document.write('                                                            media="all" type="video/mp4">');
// document.write('                                                    </video>');
// document.write('                                                    <p>Video Animations</p>');
// document.write('                                                </a>');
// document.write('                                            </li>');
// document.write('                                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/Mjk%3D"');
// document.write('                                                    title="Concept Animations">');
// document.write('                                                    <video autoplay="" loop="" muted=""');
// document.write('                                                        class="img-image"');
// document.write('                                                        style="height: 112px;visibility: visible;">');
// document.write('                                                        <source');
// document.write('                                                            src="http://cdn.thecadco.com.s3.amazonaws.com/assets/admin/uploads/doc/portfolio/29/520997614_thumb.mp4"');
// document.write('                                                            media="all" type="video/mp4">');
// document.write('                                                    </video>');
// document.write('                                                    <p>Concept Animations</p>');
// document.write('                                                </a>');
// document.write('                                            </li>');
// document.write('                                            <li> <a href="http://www.thecadco.com/site/pages/portfolio/MzA%3D"');
// document.write('                                                    title="Interactive Animation">');
// document.write('                                                    <img src="./The CAD Co_files/saved_resource"');
// document.write('                                                        class="img-fluid mCS_img_loaded">');
// document.write('                                                    <p>Interactive Animation</p>');
// document.write('                                                </a>');
// document.write('                                            </li>');
// document.write('                                        </ul>');
// document.write('                                    </div>');
// document.write('                                </div>');
// document.write('                            </div>');
// document.write('');
// document.write('                        </div>');
// document.write('                    </div>');
// document.write('                </div>');
// document.write('            </div>');
// document.write('        </div>');
// document.write('    </section>');
document.write('</div>');
document.write('<!-- navbar-collapse -->');
document.write('<!-- Brand -->');
document.write('<div class="navbar-brand mb-0 logo-container col text-center">');
document.write('<a href="../index.html">');
document.write('    <img src="../src/images/logo.png" class="img-fluid animated fadeInUp" alt="AJ Design"');
document.write('        title="AJ Design" />');
document.write('</a>');
document.write('</div>');
document.write('<!-- Brand -->');
document.write('</div>');
document.write('</nav>');
document.write('</div>');