document.write('<div class="col-md-12 mb-3 bg-peach rounded-pill overflow-hidden p-0">');
document.write('    <div class="d-flex">');
document.write('        <div class="bg-brown flex-fill p-2 text-center font-weight-bold text-white">');
document.write('            Quotes for the Day');
document.write('                                </div>');
document.write('        <div class="px-4 flex-grow-1 w-75">');
document.write('            <marquee scrollamount="5" class="m-0 pt-2">The best place for worship for Hindu');
document.write('            Сommunity | हिंदू Сommunity के लिए पूजा के लिए सबसे अच्छी जगह | હિન્દુ સર્વશક્તિ માટ');
document.write('            પૂજા માટેનું શ્રેષ્ઠ સ્થળ');
document.write('                                    </marquee>');
document.write('        </div>');
document.write('    </div>');
document.write('</div>');